# Generated by Django 4.2.3 on 2023-08-23 15:12

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0036_alter_blooddonate_blood_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonate',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('AB+', 'AB+'), ('B-', 'B-'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('A', 'A'), ('B+', 'B+'), ('A+', 'A+')], max_length=3),
        ),
        migrations.AlterField(
            model_name='blooddonate',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 23, 18, 12, 35, 867766)),
        ),
        migrations.AlterField(
            model_name='blooddonate',
            name='donation_id',
            field=models.CharField(default=uuid.UUID('5503d8cb-01bb-4ea6-a6ff-580bec175f82'), max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='blooddonate',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='donationtype',
            name='type',
            field=models.CharField(choices=[('Plasma', 'Plasma'), ('Platelets', 'Platelets'), ('Power Red', 'Power Red'), ('Blood', 'Blood')], default='Blood', max_length=10),
        ),
        migrations.AlterField(
            model_name='donor',
            name='bloodgroup',
            field=models.CharField(choices=[('AB+', 'AB+'), ('B-', 'B-'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('A', 'A'), ('B+', 'B+'), ('A+', 'A+')], default='None', max_length=10),
        ),
        migrations.AlterField(
            model_name='donor',
            name='county',
            field=models.CharField(choices=[('Bomet', 'Bomet'), ('West Pokot', 'West Pokot'), ('Meru', 'Meru'), ('Wajir', 'Wajir'), ('Lamu', 'Lamu'), ('Bungoma', 'Bungoma'), ('Tana River', 'Tana River'), ('Narok', 'Narok'), ('Kisumu', 'Kisumu'), ('Nakuru', 'Nakuru'), ('Kitui', 'Kitui'), ('Homa Bay', 'Homa Bay'), ('Kericho', 'Kericho'), ('Mandera', 'Mandera'), ('Nandi', 'Nandi'), ('Nyandarua', 'Nyandarua'), ('Garissa', 'Garissa'), ('Makueni', 'Makueni'), ('Uasin Gishu', 'Uasin Gishu'), ('Kirinyaga', 'Kirinyaga'), ('Marsabit', 'Marsabit'), ('Migori', 'Migori'), ('Kisii', 'Kisii'), ('Vihiga', 'Vihiga'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Baringo', 'Baringo'), ('Mombasa', 'Mombasa'), ('Kiambu', 'Kiambu'), ('Kilifi', 'Kilifi'), ('Embu', 'Embu'), ('Taita-Taveta', 'Taita-Taveta'), ('Trans Nzoia', 'Trans Nzoia'), ('Nyamira', 'Nyamira'), ('Machakos', 'Machakos'), ('Kajiado', 'Kajiado'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Samburu', 'Samburu'), ('Kwale', 'Kwale'), ("Murang'a", "Murang'a"), ('Nairobi', 'Nairobi'), ('Turkana', 'Turkana'), ('Laikipia', 'Laikipia'), ('Siaya', 'Siaya'), ('Nyeri', 'Nyeri'), ('Busia', 'Busia'), ('Kakamega', 'Kakamega'), ('Isiolo', 'Homa Bay')], default='None', max_length=15),
        ),
        migrations.AlterField(
            model_name='donor',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 23, 18, 12, 35, 862768)),
        ),
        migrations.AlterField(
            model_name='donor',
            name='donor_id',
            field=models.CharField(default=uuid.UUID('85055f58-45f3-4714-b8a2-545666304f73'), max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='donor',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=8),
        ),
        migrations.AlterField(
            model_name='donorhealthinfo',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('AB+', 'AB+'), ('B-', 'B-'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('A', 'A'), ('B+', 'B+'), ('A+', 'A+')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='donorhealthinfo',
            name='gender',
            field=models.CharField(choices=[('Nil', 'Nil'), ('M', 'M'), ('F', 'F')], default='Nil', max_length=3),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 23, 18, 12, 35, 868765)),
        ),
        migrations.AlterField(
            model_name='preexaminfo',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 23, 18, 12, 35, 865767)),
        ),
        migrations.AlterField(
            model_name='preexaminfo',
            name='pre_exam_id',
            field=models.CharField(default=uuid.UUID('1bd57ea2-c4af-4a83-b0d2-36b7f977c6e5'), max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='preexaminfo',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=8),
        ),
    ]
