# Generated by Django 4.2.3 on 2023-08-23 15:29

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0037_alter_blooddonate_blood_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonate',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('O+', 'O+'), ('B+', 'B+'), ('AB+', 'AB+'), ('B-', 'B-'), ('O-', 'O-'), ('A+', 'A+'), ('A', 'A'), ('AB-', 'AB-')], max_length=3),
        ),
        migrations.AlterField(
            model_name='blooddonate',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 23, 18, 29, 6, 33827)),
        ),
        migrations.AlterField(
            model_name='blooddonate',
            name='donation_id',
            field=models.CharField(default=uuid.UUID('2a84dbd5-c63f-4049-b027-56ff9528245a'), max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='blooddonate',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='donationtype',
            name='type',
            field=models.CharField(choices=[('Blood', 'Blood'), ('Platelets', 'Platelets'), ('Power Red', 'Power Red'), ('Plasma', 'Plasma')], default='Blood', max_length=10),
        ),
        migrations.AlterField(
            model_name='donor',
            name='bloodgroup',
            field=models.CharField(choices=[('O+', 'O+'), ('B+', 'B+'), ('AB+', 'AB+'), ('B-', 'B-'), ('O-', 'O-'), ('A+', 'A+'), ('A', 'A'), ('AB-', 'AB-')], default='None', max_length=10),
        ),
        migrations.AlterField(
            model_name='donor',
            name='county',
            field=models.CharField(choices=[('Vihiga', 'Vihiga'), ('Kirinyaga', 'Kirinyaga'), ('Bungoma', 'Bungoma'), ("Murang'a", "Murang'a"), ('Busia', 'Busia'), ('Turkana', 'Turkana'), ('Machakos', 'Machakos'), ('Kitui', 'Kitui'), ('Mombasa', 'Mombasa'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Nandi', 'Nandi'), ('Narok', 'Narok'), ('Garissa', 'Garissa'), ('Kiambu', 'Kiambu'), ('Migori', 'Migori'), ('Bomet', 'Bomet'), ('Homa Bay', 'Homa Bay'), ('Nyandarua', 'Nyandarua'), ('Nairobi', 'Nairobi'), ('Siaya', 'Siaya'), ('Nyamira', 'Nyamira'), ('West Pokot', 'West Pokot'), ('Tana River', 'Tana River'), ('Laikipia', 'Laikipia'), ('Meru', 'Meru'), ('Isiolo', 'Homa Bay'), ('Lamu', 'Lamu'), ('Kilifi', 'Kilifi'), ('Kericho', 'Kericho'), ('Kakamega', 'Kakamega'), ('Wajir', 'Wajir'), ('Nakuru', 'Nakuru'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Taita-Taveta', 'Taita-Taveta'), ('Kwale', 'Kwale'), ('Kisii', 'Kisii'), ('Makueni', 'Makueni'), ('Kisumu', 'Kisumu'), ('Marsabit', 'Marsabit'), ('Mandera', 'Mandera'), ('Kajiado', 'Kajiado'), ('Trans Nzoia', 'Trans Nzoia'), ('Uasin Gishu', 'Uasin Gishu'), ('Embu', 'Embu'), ('Baringo', 'Baringo'), ('Samburu', 'Samburu'), ('Nyeri', 'Nyeri')], default='None', max_length=15),
        ),
        migrations.AlterField(
            model_name='donor',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 23, 18, 29, 6, 24833)),
        ),
        migrations.AlterField(
            model_name='donor',
            name='donor_id',
            field=models.CharField(default=uuid.UUID('08a6ac73-e93f-4557-b05a-9829ff7174e1'), max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='donor',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=8),
        ),
        migrations.AlterField(
            model_name='donorhealthinfo',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('O+', 'O+'), ('B+', 'B+'), ('AB+', 'AB+'), ('B-', 'B-'), ('O-', 'O-'), ('A+', 'A+'), ('A', 'A'), ('AB-', 'AB-')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='donorhealthinfo',
            name='gender',
            field=models.CharField(choices=[('F', 'F'), ('Nil', 'Nil'), ('M', 'M')], default='Nil', max_length=3),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 23, 18, 29, 6, 35827)),
        ),
        migrations.AlterField(
            model_name='preexaminfo',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 23, 18, 29, 6, 31830)),
        ),
        migrations.AlterField(
            model_name='preexaminfo',
            name='pre_exam_id',
            field=models.CharField(default=uuid.UUID('8278d460-7a91-4154-a1c4-b7a9fcd44d8f'), max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='preexaminfo',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=8),
        ),
    ]
