# Generated by Django 4.2.3 on 2023-08-23 20:09

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0040_alter_blooddonate_blood_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonate',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('O-', 'O-'), ('O+', 'O+'), ('AB+', 'AB+'), ('A+', 'A+'), ('B+', 'B+'), ('B-', 'B-'), ('AB-', 'AB-')], max_length=3),
        ),
        migrations.AlterField(
            model_name='blooddonate',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 23, 23, 9, 43, 509349)),
        ),
        migrations.AlterField(
            model_name='blooddonate',
            name='donation_id',
            field=models.CharField(default=uuid.UUID('eba57ab4-866c-47dd-bf2a-0f8db87c0ffd'), max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='donationtype',
            name='type',
            field=models.CharField(choices=[('Power Red', 'Power Red'), ('Plasma', 'Plasma'), ('Blood', 'Blood'), ('Platelets', 'Platelets')], default='Blood', max_length=10),
        ),
        migrations.AlterField(
            model_name='donor',
            name='bloodgroup',
            field=models.CharField(choices=[('A', 'A'), ('O-', 'O-'), ('O+', 'O+'), ('AB+', 'AB+'), ('A+', 'A+'), ('B+', 'B+'), ('B-', 'B-'), ('AB-', 'AB-')], default='None', max_length=10),
        ),
        migrations.AlterField(
            model_name='donor',
            name='county',
            field=models.CharField(choices=[('Nyamira', 'Nyamira'), ('Kirinyaga', 'Kirinyaga'), ('Nakuru', 'Nakuru'), ('Meru', 'Meru'), ('Mandera', 'Mandera'), ('Garissa', 'Garissa'), ('Kakamega', 'Kakamega'), ('Nyandarua', 'Nyandarua'), ('Bungoma', 'Bungoma'), ('Samburu', 'Samburu'), ('Laikipia', 'Laikipia'), ('Homa Bay', 'Homa Bay'), ('Taita-Taveta', 'Taita-Taveta'), ("Murang'a", "Murang'a"), ('Baringo', 'Baringo'), ('Kwale', 'Kwale'), ('Lamu', 'Lamu'), ('Trans Nzoia', 'Trans Nzoia'), ('Vihiga', 'Vihiga'), ('Narok', 'Narok'), ('Embu', 'Embu'), ('Kitui', 'Kitui'), ('Kiambu', 'Kiambu'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Kilifi', 'Kilifi'), ('Migori', 'Migori'), ('West Pokot', 'West Pokot'), ('Siaya', 'Siaya'), ('Tana River', 'Tana River'), ('Wajir', 'Wajir'), ('Turkana', 'Turkana'), ('Kisii', 'Kisii'), ('Nairobi', 'Nairobi'), ('Kericho', 'Kericho'), ('Makueni', 'Makueni'), ('Bomet', 'Bomet'), ('Isiolo', 'Homa Bay'), ('Marsabit', 'Marsabit'), ('Machakos', 'Machakos'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Nandi', 'Nandi'), ('Nyeri', 'Nyeri'), ('Busia', 'Busia'), ('Mombasa', 'Mombasa'), ('Uasin Gishu', 'Uasin Gishu'), ('Kajiado', 'Kajiado'), ('Kisumu', 'Kisumu')], default='None', max_length=15),
        ),
        migrations.AlterField(
            model_name='donor',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 23, 23, 9, 43, 494356)),
        ),
        migrations.AlterField(
            model_name='donor',
            name='donor_id',
            field=models.CharField(default=uuid.UUID('b242daba-94d9-4b53-b0a3-b2a5da29de11'), max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='donorhealthinfo',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('O-', 'O-'), ('O+', 'O+'), ('AB+', 'AB+'), ('A+', 'A+'), ('B+', 'B+'), ('B-', 'B-'), ('AB-', 'AB-')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 23, 23, 9, 43, 511348)),
        ),
        migrations.AlterField(
            model_name='preexaminfo',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 23, 23, 9, 43, 500353)),
        ),
        migrations.AlterField(
            model_name='preexaminfo',
            name='pre_exam_id',
            field=models.CharField(default=uuid.UUID('de720ecd-8527-4554-a53d-12c3c008d6a9'), max_length=10, primary_key=True, serialize=False),
        ),
    ]
