# Generated by Django 4.2.3 on 2023-08-24 03:39

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0041_alter_blooddonate_blood_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonate',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('O+', 'O+'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('A+', 'A+'), ('B+', 'B+'), ('A', 'A'), ('O-', 'O-'), ('B-', 'B-')], max_length=3),
        ),
        migrations.AlterField(
            model_name='blooddonate',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 24, 6, 39, 22, 253944)),
        ),
        migrations.AlterField(
            model_name='blooddonate',
            name='donation_id',
            field=models.CharField(default=uuid.UUID('f15b9790-f743-4f2b-bb41-cf5ad566bf1c'), max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='blooddonate',
            name='status',
            field=models.CharField(choices=[('Rejected', 'Rejected'), ('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='donationtype',
            name='type',
            field=models.CharField(choices=[('Blood', 'Blood'), ('Power Red', 'Power Red'), ('Platelets', 'Platelets'), ('Plasma', 'Plasma')], default='Blood', max_length=10),
        ),
        migrations.AlterField(
            model_name='donor',
            name='bloodgroup',
            field=models.CharField(choices=[('O+', 'O+'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('A+', 'A+'), ('B+', 'B+'), ('A', 'A'), ('O-', 'O-'), ('B-', 'B-')], default='None', max_length=10),
        ),
        migrations.AlterField(
            model_name='donor',
            name='county',
            field=models.CharField(choices=[('Meru', 'Meru'), ('Busia', 'Busia'), ('Bomet', 'Bomet'), ('Mandera', 'Mandera'), ('Vihiga', 'Vihiga'), ('Nyeri', 'Nyeri'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Mombasa', 'Mombasa'), ('Nairobi', 'Nairobi'), ('Kisumu', 'Kisumu'), ('Kisii', 'Kisii'), ("Murang'a", "Murang'a"), ('Tana River', 'Tana River'), ('Makueni', 'Makueni'), ('Laikipia', 'Laikipia'), ('Lamu', 'Lamu'), ('Nakuru', 'Nakuru'), ('Homa Bay', 'Homa Bay'), ('Nandi', 'Nandi'), ('Kiambu', 'Kiambu'), ('Turkana', 'Turkana'), ('West Pokot', 'West Pokot'), ('Garissa', 'Garissa'), ('Kwale', 'Kwale'), ('Migori', 'Migori'), ('Kakamega', 'Kakamega'), ('Kericho', 'Kericho'), ('Samburu', 'Samburu'), ('Trans Nzoia', 'Trans Nzoia'), ('Wajir', 'Wajir'), ('Kilifi', 'Kilifi'), ('Nyandarua', 'Nyandarua'), ('Uasin Gishu', 'Uasin Gishu'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Taita-Taveta', 'Taita-Taveta'), ('Kirinyaga', 'Kirinyaga'), ('Embu', 'Embu'), ('Kitui', 'Kitui'), ('Isiolo', 'Homa Bay'), ('Nyamira', 'Nyamira'), ('Narok', 'Narok'), ('Bungoma', 'Bungoma'), ('Machakos', 'Machakos'), ('Kajiado', 'Kajiado'), ('Siaya', 'Siaya'), ('Marsabit', 'Marsabit'), ('Baringo', 'Baringo')], default='None', max_length=15),
        ),
        migrations.AlterField(
            model_name='donor',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 24, 6, 39, 22, 249947)),
        ),
        migrations.AlterField(
            model_name='donor',
            name='donor_id',
            field=models.CharField(default=uuid.UUID('b0245c9a-e2c3-48c3-8a4b-19995f0d8687'), max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='donor',
            name='status',
            field=models.CharField(choices=[('Rejected', 'Rejected'), ('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=8),
        ),
        migrations.AlterField(
            model_name='donorhealthinfo',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('O+', 'O+'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('A+', 'A+'), ('B+', 'B+'), ('A', 'A'), ('O-', 'O-'), ('B-', 'B-')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='donorhealthinfo',
            name='gender',
            field=models.CharField(choices=[('Nil', 'Nil'), ('F', 'F'), ('M', 'M')], default='Nil', max_length=3),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 24, 6, 39, 22, 254945)),
        ),
        migrations.AlterField(
            model_name='preexaminfo',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 24, 6, 39, 22, 251945)),
        ),
        migrations.AlterField(
            model_name='preexaminfo',
            name='pre_exam_id',
            field=models.CharField(default=uuid.UUID('0e58c201-636e-4e46-acb3-2d13ef455839'), max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='preexaminfo',
            name='status',
            field=models.CharField(choices=[('Rejected', 'Rejected'), ('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=8),
        ),
    ]
