# Generated by Django 4.2.3 on 2023-08-23 15:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('station_id', models.CharField(default=uuid.UUID('4bd50c74-1aee-488d-9b79-55c9fd681a3e'), max_length=40, primary_key=True, serialize=False)),
                ('station_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PoliceRegistration',
            fields=[
                ('police_id', models.CharField(default=uuid.UUID('0f2ebe62-62da-4524-a2a6-4072a92d5961'), max_length=40, primary_key=True, serialize=False)),
                ('profile_pic', models.ImageField(blank=True, default='profile/Police/default.png', null=True, upload_to='profile_pic/Police/')),
                ('mobile', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(default='test@test.com', max_length=254)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2023, 8, 23, 18, 29, 6, 60811))),
                ('station_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='police.station')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OccurenceRecords',
            fields=[
                ('record_id', models.CharField(default=uuid.UUID('a5580509-3a18-4923-9b5a-d62e0c7df952'), max_length=40, primary_key=True, serialize=False)),
                ('station_id', models.CharField(default='x', max_length=50, null=True)),
                ('user_id', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=8)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2023, 8, 23, 18, 29, 6, 64811))),
                ('police', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='police.policeregistration')),
            ],
        ),
    ]
