# Generated by Django 4.2.3 on 2023-08-23 19:57

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0002_alter_occurencerecords_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurencerecords',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 23, 22, 57, 18, 111008)),
        ),
        migrations.AlterField(
            model_name='occurencerecords',
            name='record_id',
            field=models.CharField(default=uuid.UUID('2aba1a7b-f346-4f4d-8cde-b5335933006e'), max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='occurencerecords',
            name='status',
            field=models.CharField(choices=[('Rejected', 'Rejected'), ('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=8),
        ),
        migrations.AlterField(
            model_name='policeregistration',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 23, 22, 57, 18, 107009)),
        ),
        migrations.AlterField(
            model_name='policeregistration',
            name='police_id',
            field=models.CharField(default=uuid.UUID('a54f8678-ffe0-4358-8d90-65097a8bbaa1'), max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='station',
            name='station_id',
            field=models.CharField(default=uuid.UUID('dedbf23d-462e-4595-864b-a4a2de757d28'), max_length=40, primary_key=True, serialize=False),
        ),
    ]
