# Generated by Django 4.2.3 on 2023-08-23 20:09

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0003_alter_occurencerecords_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurencerecords',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 23, 23, 9, 43, 565315)),
        ),
        migrations.AlterField(
            model_name='occurencerecords',
            name='record_id',
            field=models.CharField(default=uuid.UUID('f37106e5-09f0-43b7-96e6-b1ebb5de2bf4'), max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='occurencerecords',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=8),
        ),
        migrations.AlterField(
            model_name='policeregistration',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 23, 23, 9, 43, 564315)),
        ),
        migrations.AlterField(
            model_name='policeregistration',
            name='police_id',
            field=models.CharField(default=uuid.UUID('acd98163-cfac-4d78-9477-653a9abb8535'), max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='station',
            name='station_id',
            field=models.CharField(default=uuid.UUID('d9d38a81-b939-4345-b79c-b65f713ad320'), max_length=40, primary_key=True, serialize=False),
        ),
    ]
