# Generated by Django 4.2.3 on 2023-08-24 03:39

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0004_alter_occurencerecords_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurencerecords',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 24, 6, 39, 22, 274933)),
        ),
        migrations.AlterField(
            model_name='occurencerecords',
            name='record_id',
            field=models.CharField(default=uuid.UUID('82823fc9-ae75-4057-a04c-2b7a297eaa5c'), max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='occurencerecords',
            name='status',
            field=models.CharField(choices=[('Rejected', 'Rejected'), ('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=8),
        ),
        migrations.AlterField(
            model_name='policeregistration',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 24, 6, 39, 22, 273932)),
        ),
        migrations.AlterField(
            model_name='policeregistration',
            name='police_id',
            field=models.CharField(default=uuid.UUID('bb950b67-f246-49e9-9426-1b1414c67410'), max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='station',
            name='station_id',
            field=models.CharField(default=uuid.UUID('011d1953-4e07-41ca-83c8-71eb78dc3abf'), max_length=40, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('report_id', models.CharField(default=uuid.UUID('2c433948-bf46-4fb4-be0e-be45234f6eff'), max_length=50, primary_key=True, serialize=False)),
                ('station_id', models.CharField(default='x', max_length=50, null=True)),
                ('title', models.CharField(default='Donation-report', max_length=100)),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/user-reports/')),
                ('created_at', models.DateTimeField()),
                ('police', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='police.policeregistration')),
            ],
        ),
        migrations.CreateModel(
            name='OccurenceReport',
            fields=[
                ('report_id', models.CharField(default=uuid.UUID('336b084e-5220-4b45-b14b-8729b1404ae1'), max_length=50, primary_key=True, serialize=False)),
                ('station_id', models.CharField(default='x', max_length=50, null=True)),
                ('title', models.CharField(default='Occurence-report', max_length=100)),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/occurence-reports/')),
                ('created_at', models.DateTimeField()),
                ('police', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='police.policeregistration')),
            ],
        ),
    ]
