# Generated by Django 4.2.3 on 2023-08-23 15:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0020_alter_donationreport_report_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationreport',
            name='report_id',
            field=models.CharField(default=uuid.UUID('ba3e22be-e546-46dc-93a9-04765b46f586'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='donorreport',
            name='report_id',
            field=models.CharField(default=uuid.UUID('9aab57c8-02d9-4248-b21c-4d64eefe16db'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='preexamsreport',
            name='report_id',
            field=models.CharField(default=uuid.UUID('f5104c70-3004-4aa6-a94b-4045d6bde944'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stationreport',
            name='report_id',
            field=models.CharField(default=uuid.UUID('13ce3a4b-0b4a-4994-a8bb-d1f9389955db'), max_length=50, primary_key=True, serialize=False),
        ),
    ]
