# Generated by Django 4.2.3 on 2023-08-23 15:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0021_alter_donationreport_report_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationreport',
            name='report_id',
            field=models.CharField(default=uuid.UUID('252fe4b5-69e2-44e9-b4fe-ccd412d19f78'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='donorreport',
            name='report_id',
            field=models.CharField(default=uuid.UUID('343fe7a8-6b67-4049-a085-eb56fef0c8a3'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='preexamsreport',
            name='report_id',
            field=models.CharField(default=uuid.UUID('40cf233d-e201-4f8a-b52f-c74704c0b488'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stationreport',
            name='report_id',
            field=models.CharField(default=uuid.UUID('218626e1-ead9-4c41-96f9-c601141165cf'), max_length=50, primary_key=True, serialize=False),
        ),
    ]
