# Generated by Django 4.2.3 on 2023-08-23 17:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0022_alter_donationreport_report_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationreport',
            name='report_id',
            field=models.CharField(default=uuid.UUID('43a0a781-3add-4b14-9a3d-6e12fb3bbff1'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='donorreport',
            name='report_id',
            field=models.CharField(default=uuid.UUID('03fc2f70-7ed2-4c23-a316-807f2d28f082'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='preexamsreport',
            name='report_id',
            field=models.CharField(default=uuid.UUID('02031b58-02a3-408a-b42e-b956b5268c34'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stationreport',
            name='report_id',
            field=models.CharField(default=uuid.UUID('1c038deb-2806-4e6e-ab29-db41e1b45926'), max_length=50, primary_key=True, serialize=False),
        ),
    ]
