# Generated by Django 4.2.3 on 2023-08-23 19:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0023_alter_donationreport_report_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationreport',
            name='report_id',
            field=models.CharField(default=uuid.UUID('a1ab2820-4f74-40f8-b589-3e8bb54e23ec'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='donorreport',
            name='report_id',
            field=models.CharField(default=uuid.UUID('83d82292-7751-4487-b296-a88a45399312'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='preexamsreport',
            name='report_id',
            field=models.CharField(default=uuid.UUID('0d124d71-c3c5-400c-88c1-7bd6512bd2a6'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stationreport',
            name='report_id',
            field=models.CharField(default=uuid.UUID('2d34d105-e8c2-4f34-9b92-11352229a7db'), max_length=50, primary_key=True, serialize=False),
        ),
    ]
