# Generated by Django 4.2.3 on 2023-08-23 15:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0048_alter_hostedblooddrives_county_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostedblooddrives',
            name='county',
            field=models.CharField(choices=[('Bomet', 'Bomet'), ('Meru', 'Meru'), ('West Pokot', 'West Pokot'), ('Wajir', 'Wajir'), ('Lamu', 'Lamu'), ('Bungoma', 'Bungoma'), ('Tana River', 'Tana River'), ('Narok', 'Narok'), ('Kisumu', 'Kisumu'), ('Nakuru', 'Nakuru'), ('Kitui', 'Kitui'), ('Homa Bay', 'Homa Bay'), ('Kericho', 'Kericho'), ('Mandera', 'Mandera'), ('Nandi', 'Nandi'), ('Nyandarua', 'Nyandarua'), ("Murang'a", 'Murang'), ('Garissa', 'Garissa'), ('Makueni', 'Makueni'), ('Uasin Gishu', 'Uasin Gishu'), ('Kirinyaga', 'Kirinyaga'), ('Marsabit', 'Marsabit'), ('Migori', 'Migori'), ('Kisii', 'Kisii'), ('Vihiga', 'Vihiga'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Baringo', 'Baringo'), ('Mombasa', 'Mombasa'), ('Kiambu', 'Kiambu'), ('Kilifi', 'Kilifi'), ('Embu', 'Embu'), ('Kakamega', 'Kakamega'), ('Taita-Taveta', 'Taita-Taveta'), ('Trans Nzoia', 'Trans Nzoia'), ('Nyamira', 'Nyamira'), ('Machakos', 'Machakos'), ('Kajiado', 'Kajiado'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Samburu', 'Samburu'), ('Nairobi', 'Nairobi'), ('Kwale', 'Kwale'), ('Turkana', 'Turkana'), ('Laikipia', 'Laikipia'), ('Siaya', 'Siaya'), ('Nyeri', 'Nyeri'), ('Busia', 'Busia'), ('Isiolo', 'Homa Bay')], max_length=15),
        ),
        migrations.AlterField(
            model_name='volunteerregistration',
            name='location',
            field=models.CharField(choices=[('Bomet', 'Bomet'), ('Meru', 'Meru'), ('West Pokot', 'West Pokot'), ('Wajir', 'Wajir'), ('Lamu', 'Lamu'), ('Bungoma', 'Bungoma'), ('Tana River', 'Tana River'), ('Narok', 'Narok'), ('Kisumu', 'Kisumu'), ('Nakuru', 'Nakuru'), ('Kitui', 'Kitui'), ('Homa Bay', 'Homa Bay'), ('Kericho', 'Kericho'), ('Mandera', 'Mandera'), ('Nandi', 'Nandi'), ('Nyandarua', 'Nyandarua'), ("Murang'a", 'Murang'), ('Garissa', 'Garissa'), ('Makueni', 'Makueni'), ('Uasin Gishu', 'Uasin Gishu'), ('Kirinyaga', 'Kirinyaga'), ('Marsabit', 'Marsabit'), ('Migori', 'Migori'), ('Kisii', 'Kisii'), ('Vihiga', 'Vihiga'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Baringo', 'Baringo'), ('Mombasa', 'Mombasa'), ('Kiambu', 'Kiambu'), ('Kilifi', 'Kilifi'), ('Embu', 'Embu'), ('Kakamega', 'Kakamega'), ('Taita-Taveta', 'Taita-Taveta'), ('Trans Nzoia', 'Trans Nzoia'), ('Nyamira', 'Nyamira'), ('Machakos', 'Machakos'), ('Kajiado', 'Kajiado'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Samburu', 'Samburu'), ('Nairobi', 'Nairobi'), ('Kwale', 'Kwale'), ('Turkana', 'Turkana'), ('Laikipia', 'Laikipia'), ('Siaya', 'Siaya'), ('Nyeri', 'Nyeri'), ('Busia', 'Busia'), ('Isiolo', 'Homa Bay')], max_length=100),
        ),
        migrations.AlterField(
            model_name='volunteerregistration',
            name='volunteer_id',
            field=models.CharField(default=uuid.UUID('6ab985f5-6bc8-4276-aab9-9d958a91a2ba'), max_length=20, primary_key=True, serialize=False),
        ),
    ]
