# Generated by Django 4.2.3 on 2023-08-23 15:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0049_alter_hostedblooddrives_county_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostedblooddrives',
            name='county',
            field=models.CharField(choices=[('Vihiga', 'Vihiga'), ('Kirinyaga', 'Kirinyaga'), ('Bungoma', 'Bungoma'), ('Busia', 'Busia'), ('Turkana', 'Turkana'), ('Machakos', 'Machakos'), ('Kitui', 'Kitui'), ('Mombasa', 'Mombasa'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Nandi', 'Nandi'), ('Garissa', 'Garissa'), ('Homa Bay', 'Homa Bay'), ('Migori', 'Migori'), ('Kiambu', 'Kiambu'), ('Bomet', 'Bomet'), ('Narok', 'Narok'), ("Murang'a", 'Murang'), ('Nyandarua', 'Nyandarua'), ('Nairobi', 'Nairobi'), ('Siaya', 'Siaya'), ('Nyamira', 'Nyamira'), ('West Pokot', 'West Pokot'), ('Tana River', 'Tana River'), ('Meru', 'Meru'), ('Laikipia', 'Laikipia'), ('Isiolo', 'Homa Bay'), ('Lamu', 'Lamu'), ('Kilifi', 'Kilifi'), ('Kericho', 'Kericho'), ('Kakamega', 'Kakamega'), ('Wajir', 'Wajir'), ('Nakuru', 'Nakuru'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Taita-Taveta', 'Taita-Taveta'), ('Kisii', 'Kisii'), ('Kisumu', 'Kisumu'), ('Makueni', 'Makueni'), ('Kwale', 'Kwale'), ('Mandera', 'Mandera'), ('Marsabit', 'Marsabit'), ('Kajiado', 'Kajiado'), ('Trans Nzoia', 'Trans Nzoia'), ('Uasin Gishu', 'Uasin Gishu'), ('Embu', 'Embu'), ('Baringo', 'Baringo'), ('Samburu', 'Samburu'), ('Nyeri', 'Nyeri')], max_length=15),
        ),
        migrations.AlterField(
            model_name='volunteerregistration',
            name='location',
            field=models.CharField(choices=[('Vihiga', 'Vihiga'), ('Kirinyaga', 'Kirinyaga'), ('Bungoma', 'Bungoma'), ('Busia', 'Busia'), ('Turkana', 'Turkana'), ('Machakos', 'Machakos'), ('Kitui', 'Kitui'), ('Mombasa', 'Mombasa'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Nandi', 'Nandi'), ('Garissa', 'Garissa'), ('Homa Bay', 'Homa Bay'), ('Migori', 'Migori'), ('Kiambu', 'Kiambu'), ('Bomet', 'Bomet'), ('Narok', 'Narok'), ("Murang'a", 'Murang'), ('Nyandarua', 'Nyandarua'), ('Nairobi', 'Nairobi'), ('Siaya', 'Siaya'), ('Nyamira', 'Nyamira'), ('West Pokot', 'West Pokot'), ('Tana River', 'Tana River'), ('Meru', 'Meru'), ('Laikipia', 'Laikipia'), ('Isiolo', 'Homa Bay'), ('Lamu', 'Lamu'), ('Kilifi', 'Kilifi'), ('Kericho', 'Kericho'), ('Kakamega', 'Kakamega'), ('Wajir', 'Wajir'), ('Nakuru', 'Nakuru'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Taita-Taveta', 'Taita-Taveta'), ('Kisii', 'Kisii'), ('Kisumu', 'Kisumu'), ('Makueni', 'Makueni'), ('Kwale', 'Kwale'), ('Mandera', 'Mandera'), ('Marsabit', 'Marsabit'), ('Kajiado', 'Kajiado'), ('Trans Nzoia', 'Trans Nzoia'), ('Uasin Gishu', 'Uasin Gishu'), ('Embu', 'Embu'), ('Baringo', 'Baringo'), ('Samburu', 'Samburu'), ('Nyeri', 'Nyeri')], max_length=100),
        ),
        migrations.AlterField(
            model_name='volunteerregistration',
            name='volunteer_id',
            field=models.CharField(default=uuid.UUID('c394dd82-9c0d-4ab7-96d0-008101a3dc6d'), max_length=20, primary_key=True, serialize=False),
        ),
    ]
