# Generated by Django 4.2.3 on 2023-08-23 17:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0050_alter_hostedblooddrives_county_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostedblooddrives',
            name='county',
            field=models.CharField(choices=[('Siaya', 'Siaya'), ('Kisumu', 'Kisumu'), ('Kajiado', 'Kajiado'), ('Nyamira', 'Nyamira'), ('Garissa', 'Garissa'), ('Mombasa', 'Mombasa'), ('Migori', 'Migori'), ('Isiolo', 'Homa Bay'), ('Bomet', 'Bomet'), ('Nandi', 'Nandi'), ('Kiambu', 'Kiambu'), ("Murang'a", 'Murang'), ('Vihiga', 'Vihiga'), ('Nyandarua', 'Nyandarua'), ('Tana River', 'Tana River'), ('Lamu', 'Lamu'), ('Kilifi', 'Kilifi'), ('Samburu', 'Samburu'), ('Taita-Taveta', 'Taita-Taveta'), ('Embu', 'Embu'), ('Trans Nzoia', 'Trans Nzoia'), ('Homa Bay', 'Homa Bay'), ('Kwale', 'Kwale'), ('Laikipia', 'Laikipia'), ('West Pokot', 'West Pokot'), ('Busia', 'Busia'), ('Makueni', 'Makueni'), ('Kitui', 'Kitui'), ('Kisii', 'Kisii'), ('Mandera', 'Mandera'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Nyeri', 'Nyeri'), ('Wajir', 'Wajir'), ('Kericho', 'Kericho'), ('Machakos', 'Machakos'), ('Baringo', 'Baringo'), ('Kakamega', 'Kakamega'), ('Turkana', 'Turkana'), ('Kirinyaga', 'Kirinyaga'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Uasin Gishu', 'Uasin Gishu'), ('Nairobi', 'Nairobi'), ('Bungoma', 'Bungoma'), ('Meru', 'Meru'), ('Marsabit', 'Marsabit'), ('Narok', 'Narok'), ('Nakuru', 'Nakuru')], max_length=15),
        ),
        migrations.AlterField(
            model_name='volunteerregistration',
            name='location',
            field=models.CharField(choices=[('Siaya', 'Siaya'), ('Kisumu', 'Kisumu'), ('Kajiado', 'Kajiado'), ('Nyamira', 'Nyamira'), ('Garissa', 'Garissa'), ('Mombasa', 'Mombasa'), ('Migori', 'Migori'), ('Isiolo', 'Homa Bay'), ('Bomet', 'Bomet'), ('Nandi', 'Nandi'), ('Kiambu', 'Kiambu'), ("Murang'a", 'Murang'), ('Vihiga', 'Vihiga'), ('Nyandarua', 'Nyandarua'), ('Tana River', 'Tana River'), ('Lamu', 'Lamu'), ('Kilifi', 'Kilifi'), ('Samburu', 'Samburu'), ('Taita-Taveta', 'Taita-Taveta'), ('Embu', 'Embu'), ('Trans Nzoia', 'Trans Nzoia'), ('Homa Bay', 'Homa Bay'), ('Kwale', 'Kwale'), ('Laikipia', 'Laikipia'), ('West Pokot', 'West Pokot'), ('Busia', 'Busia'), ('Makueni', 'Makueni'), ('Kitui', 'Kitui'), ('Kisii', 'Kisii'), ('Mandera', 'Mandera'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Nyeri', 'Nyeri'), ('Wajir', 'Wajir'), ('Kericho', 'Kericho'), ('Machakos', 'Machakos'), ('Baringo', 'Baringo'), ('Kakamega', 'Kakamega'), ('Turkana', 'Turkana'), ('Kirinyaga', 'Kirinyaga'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Uasin Gishu', 'Uasin Gishu'), ('Nairobi', 'Nairobi'), ('Bungoma', 'Bungoma'), ('Meru', 'Meru'), ('Marsabit', 'Marsabit'), ('Narok', 'Narok'), ('Nakuru', 'Nakuru')], max_length=100),
        ),
        migrations.AlterField(
            model_name='volunteerregistration',
            name='volunteer_id',
            field=models.CharField(default=uuid.UUID('37e057d2-9323-457f-8d39-eb6e04491ab5'), max_length=20, primary_key=True, serialize=False),
        ),
    ]
