# Generated by Django 4.2.3 on 2023-08-23 20:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0052_alter_hostedblooddrives_county_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostedblooddrives',
            name='county',
            field=models.CharField(choices=[('Nyamira', 'Nyamira'), ('Kirinyaga', 'Kirinyaga'), ('Nakuru', 'Nakuru'), ('Meru', 'Meru'), ('Mandera', 'Mandera'), ('Garissa', 'Garissa'), ('Kakamega', 'Kakamega'), ('Nyandarua', 'Nyandarua'), ('Bungoma', 'Bungoma'), ('Homa Bay', 'Homa Bay'), ('Samburu', 'Samburu'), ('Laikipia', 'Laikipia'), ('Taita-Taveta', 'Taita-Taveta'), ('Baringo', 'Baringo'), ('Kwale', 'Kwale'), ('Lamu', 'Lamu'), ('Trans Nzoia', 'Trans Nzoia'), ('Vihiga', 'Vihiga'), ('Narok', 'Narok'), ('Embu', 'Embu'), ('Kitui', 'Kitui'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Kiambu', 'Kiambu'), ('Kilifi', 'Kilifi'), ('Migori', 'Migori'), ('Siaya', 'Siaya'), ('West Pokot', 'West Pokot'), ('Tana River', 'Tana River'), ('Wajir', 'Wajir'), ('Turkana', 'Turkana'), ('Kisii', 'Kisii'), ('Nairobi', 'Nairobi'), ("Murang'a", 'Murang'), ('Kericho', 'Kericho'), ('Makueni', 'Makueni'), ('Mombasa', 'Mombasa'), ('Bomet', 'Bomet'), ('Isiolo', 'Homa Bay'), ('Marsabit', 'Marsabit'), ('Machakos', 'Machakos'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Nyeri', 'Nyeri'), ('Busia', 'Busia'), ('Uasin Gishu', 'Uasin Gishu'), ('Nandi', 'Nandi'), ('Kajiado', 'Kajiado'), ('Kisumu', 'Kisumu')], max_length=15),
        ),
        migrations.AlterField(
            model_name='volunteerregistration',
            name='location',
            field=models.CharField(choices=[('Nyamira', 'Nyamira'), ('Kirinyaga', 'Kirinyaga'), ('Nakuru', 'Nakuru'), ('Meru', 'Meru'), ('Mandera', 'Mandera'), ('Garissa', 'Garissa'), ('Kakamega', 'Kakamega'), ('Nyandarua', 'Nyandarua'), ('Bungoma', 'Bungoma'), ('Homa Bay', 'Homa Bay'), ('Samburu', 'Samburu'), ('Laikipia', 'Laikipia'), ('Taita-Taveta', 'Taita-Taveta'), ('Baringo', 'Baringo'), ('Kwale', 'Kwale'), ('Lamu', 'Lamu'), ('Trans Nzoia', 'Trans Nzoia'), ('Vihiga', 'Vihiga'), ('Narok', 'Narok'), ('Embu', 'Embu'), ('Kitui', 'Kitui'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Kiambu', 'Kiambu'), ('Kilifi', 'Kilifi'), ('Migori', 'Migori'), ('Siaya', 'Siaya'), ('West Pokot', 'West Pokot'), ('Tana River', 'Tana River'), ('Wajir', 'Wajir'), ('Turkana', 'Turkana'), ('Kisii', 'Kisii'), ('Nairobi', 'Nairobi'), ("Murang'a", 'Murang'), ('Kericho', 'Kericho'), ('Makueni', 'Makueni'), ('Mombasa', 'Mombasa'), ('Bomet', 'Bomet'), ('Isiolo', 'Homa Bay'), ('Marsabit', 'Marsabit'), ('Machakos', 'Machakos'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Nyeri', 'Nyeri'), ('Busia', 'Busia'), ('Uasin Gishu', 'Uasin Gishu'), ('Nandi', 'Nandi'), ('Kajiado', 'Kajiado'), ('Kisumu', 'Kisumu')], max_length=100),
        ),
        migrations.AlterField(
            model_name='volunteerregistration',
            name='volunteer_id',
            field=models.CharField(default=uuid.UUID('dda36e15-2c51-4081-a344-ebf4951c5939'), max_length=20, primary_key=True, serialize=False),
        ),
    ]
