# Generated by Django 4.2.3 on 2023-08-24 03:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0053_alter_hostedblooddrives_county_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostedblooddrives',
            name='county',
            field=models.CharField(choices=[('Meru', 'Meru'), ('Busia', 'Busia'), ('Bomet', 'Bomet'), ('Mandera', 'Mandera'), ('Vihiga', 'Vihiga'), ('Nyeri', 'Nyeri'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Nairobi', 'Nairobi'), ('Mombasa', 'Mombasa'), ("Murang'a", 'Murang'), ('Kisumu', 'Kisumu'), ('Kisii', 'Kisii'), ('Tana River', 'Tana River'), ('Makueni', 'Makueni'), ('Laikipia', 'Laikipia'), ('Lamu', 'Lamu'), ('Nakuru', 'Nakuru'), ('Homa Bay', 'Homa Bay'), ('Nandi', 'Nandi'), ('Kiambu', 'Kiambu'), ('Turkana', 'Turkana'), ('West Pokot', 'West Pokot'), ('Garissa', 'Garissa'), ('Kwale', 'Kwale'), ('Migori', 'Migori'), ('Kakamega', 'Kakamega'), ('Kericho', 'Kericho'), ('Samburu', 'Samburu'), ('Trans Nzoia', 'Trans Nzoia'), ('Wajir', 'Wajir'), ('Kilifi', 'Kilifi'), ('Nyandarua', 'Nyandarua'), ('Uasin Gishu', 'Uasin Gishu'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Taita-Taveta', 'Taita-Taveta'), ('Kirinyaga', 'Kirinyaga'), ('Embu', 'Embu'), ('Kitui', 'Kitui'), ('Isiolo', 'Homa Bay'), ('Nyamira', 'Nyamira'), ('Narok', 'Narok'), ('Bungoma', 'Bungoma'), ('Machakos', 'Machakos'), ('Kajiado', 'Kajiado'), ('Siaya', 'Siaya'), ('Marsabit', 'Marsabit'), ('Baringo', 'Baringo')], max_length=15),
        ),
        migrations.AlterField(
            model_name='volunteerregistration',
            name='location',
            field=models.CharField(choices=[('Meru', 'Meru'), ('Busia', 'Busia'), ('Bomet', 'Bomet'), ('Mandera', 'Mandera'), ('Vihiga', 'Vihiga'), ('Nyeri', 'Nyeri'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Nairobi', 'Nairobi'), ('Mombasa', 'Mombasa'), ("Murang'a", 'Murang'), ('Kisumu', 'Kisumu'), ('Kisii', 'Kisii'), ('Tana River', 'Tana River'), ('Makueni', 'Makueni'), ('Laikipia', 'Laikipia'), ('Lamu', 'Lamu'), ('Nakuru', 'Nakuru'), ('Homa Bay', 'Homa Bay'), ('Nandi', 'Nandi'), ('Kiambu', 'Kiambu'), ('Turkana', 'Turkana'), ('West Pokot', 'West Pokot'), ('Garissa', 'Garissa'), ('Kwale', 'Kwale'), ('Migori', 'Migori'), ('Kakamega', 'Kakamega'), ('Kericho', 'Kericho'), ('Samburu', 'Samburu'), ('Trans Nzoia', 'Trans Nzoia'), ('Wajir', 'Wajir'), ('Kilifi', 'Kilifi'), ('Nyandarua', 'Nyandarua'), ('Uasin Gishu', 'Uasin Gishu'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Taita-Taveta', 'Taita-Taveta'), ('Kirinyaga', 'Kirinyaga'), ('Embu', 'Embu'), ('Kitui', 'Kitui'), ('Isiolo', 'Homa Bay'), ('Nyamira', 'Nyamira'), ('Narok', 'Narok'), ('Bungoma', 'Bungoma'), ('Machakos', 'Machakos'), ('Kajiado', 'Kajiado'), ('Siaya', 'Siaya'), ('Marsabit', 'Marsabit'), ('Baringo', 'Baringo')], max_length=100),
        ),
        migrations.AlterField(
            model_name='volunteerregistration',
            name='volunteer_id',
            field=models.CharField(default=uuid.UUID('42a6da10-d81b-4903-947e-1077bbdcf021'), max_length=20, primary_key=True, serialize=False),
        ),
    ]
