# Generated by Django 4.2.3 on 2023-08-23 15:12

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0046_alter_blooddrives_county_alter_blooddrives_drive_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddrives',
            name='county',
            field=models.CharField(choices=[('Bomet', 'Bomet'), ('West Pokot', 'West Pokot'), ('Meru', 'Meru'), ('Wajir', 'Wajir'), ('Lamu', 'Lamu'), ('Bungoma', 'Bungoma'), ('Tana River', 'Tana River'), ('Narok', 'Narok'), ('Kisumu', 'Kisumu'), ('Nakuru', 'Nakuru'), ('Kitui', 'Kitui'), ('Homa Bay', 'Homa Bay'), ('Kericho', 'Kericho'), ('Mandera', 'Mandera'), ('Nandi', 'Nandi'), ('Nyandarua', 'Nyandarua'), ('Garissa', 'Garissa'), ('Makueni', 'Makueni'), ('Uasin Gishu', 'Uasin Gishu'), ('Kirinyaga', 'Kirinyaga'), ('Marsabit', 'Marsabit'), ('Migori', 'Migori'), ('Kisii', 'Kisii'), ('Vihiga', 'Vihiga'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Baringo', 'Baringo'), ('Mombasa', 'Mombasa'), ('Kiambu', 'Kiambu'), ('Kilifi', 'Kilifi'), ('Embu', 'Embu'), ('Taita-Taveta', 'Taita-Taveta'), ('Trans Nzoia', 'Trans Nzoia'), ('Nyamira', 'Nyamira'), ('Machakos', 'Machakos'), ('Kajiado', 'Kajiado'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Samburu', 'Samburu'), ('Kwale', 'Kwale'), ("Murang'a", "Murang'a"), ('Nairobi', 'Nairobi'), ('Turkana', 'Turkana'), ('Laikipia', 'Laikipia'), ('Siaya', 'Siaya'), ('Nyeri', 'Nyeri'), ('Busia', 'Busia'), ('Kakamega', 'Kakamega'), ('Isiolo', 'Homa Bay')], max_length=15),
        ),
        migrations.AlterField(
            model_name='blooddrives',
            name='drive_id',
            field=models.CharField(default=uuid.UUID('66b16312-161d-4d02-a953-9e26dafc0560'), max_length=60, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='blood_group',
            field=models.CharField(choices=[('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('A', 'A'), ('B+', 'B+'), ('A+', 'A+')], default='None', max_length=10),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 8, 23, 18, 12, 35, 848779)),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
