# Generated by Django 4.2.3 on 2023-08-23 19:57

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0049_alter_blooddrives_county_alter_blooddrives_drive_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddrives',
            name='county',
            field=models.CharField(choices=[('Mombasa', 'Mombasa'), ('Kilifi', 'Kilifi'), ('Kakamega', 'Kakamega'), ('Nandi', 'Nandi'), ('Bungoma', 'Bungoma'), ('Kajiado', 'Kajiado'), ('Mandera', 'Mandera'), ('Uasin Gishu', 'Uasin Gishu'), ('Nakuru', 'Nakuru'), ('Lamu', 'Lamu'), ('Taita-Taveta', 'Taita-Taveta'), ('Migori', 'Migori'), ('West Pokot', 'West Pokot'), ('Vihiga', 'Vihiga'), ('Turkana', 'Turkana'), ('Machakos', 'Machakos'), ('Busia', 'Busia'), ('Garissa', 'Garissa'), ('Isiolo', 'Homa Bay'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Kirinyaga', 'Kirinyaga'), ('Nyeri', 'Nyeri'), ('Nyandarua', 'Nyandarua'), ('Tana River', 'Tana River'), ('Kwale', 'Kwale'), ('Kiambu', 'Kiambu'), ('Marsabit', 'Marsabit'), ('Homa Bay', 'Homa Bay'), ('Nairobi', 'Nairobi'), ('Narok', 'Narok'), ('Kisii', 'Kisii'), ('Embu', 'Embu'), ('Samburu', 'Samburu'), ('Wajir', 'Wajir'), ('Kitui', 'Kitui'), ('Kisumu', 'Kisumu'), ('Nyamira', 'Nyamira'), ('Siaya', 'Siaya'), ('Meru', 'Meru'), ('Trans Nzoia', 'Trans Nzoia'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Laikipia', 'Laikipia'), ("Murang'a", "Murang'a"), ('Kericho', 'Kericho'), ('Makueni', 'Makueni'), ('Baringo', 'Baringo'), ('Bomet', 'Bomet')], max_length=15),
        ),
        migrations.AlterField(
            model_name='blooddrives',
            name='drive_id',
            field=models.CharField(default=uuid.UUID('d91e9ead-bf89-46ec-b4ac-a3af44649fb6'), max_length=60, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='blood_group',
            field=models.CharField(choices=[('AB+', 'AB+'), ('AB-', 'AB-'), ('A', 'A'), ('O-', 'O-'), ('O+', 'O+'), ('A+', 'A+'), ('B+', 'B+'), ('B-', 'B-')], default='None', max_length=10),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 8, 23, 22, 57, 18, 26066)),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
