# Generated by Django 4.2.3 on 2023-08-23 20:09

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0050_alter_blooddrives_county_alter_blooddrives_drive_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddrives',
            name='county',
            field=models.CharField(choices=[('Nyamira', 'Nyamira'), ('Kirinyaga', 'Kirinyaga'), ('Nakuru', 'Nakuru'), ('Meru', 'Meru'), ('Mandera', 'Mandera'), ('Garissa', 'Garissa'), ('Kakamega', 'Kakamega'), ('Nyandarua', 'Nyandarua'), ('Bungoma', 'Bungoma'), ('Samburu', 'Samburu'), ('Laikipia', 'Laikipia'), ('Homa Bay', 'Homa Bay'), ('Taita-Taveta', 'Taita-Taveta'), ("Murang'a", "Murang'a"), ('Baringo', 'Baringo'), ('Kwale', 'Kwale'), ('Lamu', 'Lamu'), ('Trans Nzoia', 'Trans Nzoia'), ('Vihiga', 'Vihiga'), ('Narok', 'Narok'), ('Embu', 'Embu'), ('Kitui', 'Kitui'), ('Kiambu', 'Kiambu'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Kilifi', 'Kilifi'), ('Migori', 'Migori'), ('West Pokot', 'West Pokot'), ('Siaya', 'Siaya'), ('Tana River', 'Tana River'), ('Wajir', 'Wajir'), ('Turkana', 'Turkana'), ('Kisii', 'Kisii'), ('Nairobi', 'Nairobi'), ('Kericho', 'Kericho'), ('Makueni', 'Makueni'), ('Bomet', 'Bomet'), ('Isiolo', 'Homa Bay'), ('Marsabit', 'Marsabit'), ('Machakos', 'Machakos'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Nandi', 'Nandi'), ('Nyeri', 'Nyeri'), ('Busia', 'Busia'), ('Mombasa', 'Mombasa'), ('Uasin Gishu', 'Uasin Gishu'), ('Kajiado', 'Kajiado'), ('Kisumu', 'Kisumu')], max_length=15),
        ),
        migrations.AlterField(
            model_name='blooddrives',
            name='drive_id',
            field=models.CharField(default=uuid.UUID('3cc9ab8c-fc86-4eb6-b8dc-d2bf91c34c33'), max_length=60, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='blood_group',
            field=models.CharField(choices=[('A', 'A'), ('O-', 'O-'), ('O+', 'O+'), ('AB+', 'AB+'), ('A+', 'A+'), ('B+', 'B+'), ('B-', 'B-'), ('AB-', 'AB-')], default='None', max_length=10),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 8, 23, 23, 9, 43, 474371)),
        ),
    ]
