# Generated by Django 4.2.3 on 2023-08-24 03:39

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0051_alter_blooddrives_county_alter_blooddrives_drive_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddrives',
            name='county',
            field=models.CharField(choices=[('Meru', 'Meru'), ('Busia', 'Busia'), ('Bomet', 'Bomet'), ('Mandera', 'Mandera'), ('Vihiga', 'Vihiga'), ('Nyeri', 'Nyeri'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Mombasa', 'Mombasa'), ('Nairobi', 'Nairobi'), ('Kisumu', 'Kisumu'), ('Kisii', 'Kisii'), ("Murang'a", "Murang'a"), ('Tana River', 'Tana River'), ('Makueni', 'Makueni'), ('Laikipia', 'Laikipia'), ('Lamu', 'Lamu'), ('Nakuru', 'Nakuru'), ('Homa Bay', 'Homa Bay'), ('Nandi', 'Nandi'), ('Kiambu', 'Kiambu'), ('Turkana', 'Turkana'), ('West Pokot', 'West Pokot'), ('Garissa', 'Garissa'), ('Kwale', 'Kwale'), ('Migori', 'Migori'), ('Kakamega', 'Kakamega'), ('Kericho', 'Kericho'), ('Samburu', 'Samburu'), ('Trans Nzoia', 'Trans Nzoia'), ('Wajir', 'Wajir'), ('Kilifi', 'Kilifi'), ('Nyandarua', 'Nyandarua'), ('Uasin Gishu', 'Uasin Gishu'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Taita-Taveta', 'Taita-Taveta'), ('Kirinyaga', 'Kirinyaga'), ('Embu', 'Embu'), ('Kitui', 'Kitui'), ('Isiolo', 'Homa Bay'), ('Nyamira', 'Nyamira'), ('Narok', 'Narok'), ('Bungoma', 'Bungoma'), ('Machakos', 'Machakos'), ('Kajiado', 'Kajiado'), ('Siaya', 'Siaya'), ('Marsabit', 'Marsabit'), ('Baringo', 'Baringo')], max_length=15),
        ),
        migrations.AlterField(
            model_name='blooddrives',
            name='drive_id',
            field=models.CharField(default=uuid.UUID('06917c64-e71f-44eb-ba3f-de2d1b463278'), max_length=60, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='blood_group',
            field=models.CharField(choices=[('O+', 'O+'), ('AB+', 'AB+'), ('B+', 'B+'), ('A+', 'A+'), ('AB-', 'AB-'), ('A', 'A'), ('O-', 'O-'), ('B-', 'B-')], default='None', max_length=10),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 8, 24, 6, 39, 22, 238955)),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='status',
            field=models.CharField(choices=[('Rejected', 'Rejected'), ('Approved', 'Approved'), ('Pending', 'Pending')], default='Pending', max_length=20),
        ),
    ]
