# Generated by Django 4.2.3 on 2023-08-23 19:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 23, 22, 57, 18, 100014)),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='user_no',
            field=models.CharField(default=uuid.UUID('9fd2468b-fe88-4fe0-bc8c-0c68c307b3f1'), max_length=40, primary_key=True, serialize=False),
        ),
    ]
