# Generated by Django 4.2.3 on 2023-08-24 03:39

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userregistration_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 24, 6, 39, 22, 271933)),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='user_no',
            field=models.CharField(default=uuid.UUID('8cbcb255-05bc-448e-9b88-7828947aef7f'), max_length=40, primary_key=True, serialize=False),
        ),
    ]
